#ifndef LINUX_MAIL_SLOT_HEADER
#define LINUX_MAIL_SLOT_HEADER

#define MAX_DATA_UNIT_SIZE 128
#define MAX_STORAGE (1<<20)

#define CHANGE_WRITE_BLOCKING_MODE_CTL 3
#define CHANGE_READ_BLOCKING_MODE_CTL 4
#define CHANGE_MAX_DATA_UNIT_SIZE_CTL 5
#define GET_MAX_DATA_UNIT_SIZE_CTL 6
#define GET_FREESPACE_SIZE_CTL 7
#define GET_WRITE_BLOCKING_MODE_CTL 8
#define GET_READ_BLOCKING_MODE_CTL 9

#define N 8192

#endif
